# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db3b545480d29a0bffff1c7f2e26880119ed7cc1465aee58df6be11b2168edbff59a8b4efb464e2c812fec6aa3d7d116a768a463db84cfd6d38e64bed29f95fb

test:
  secret_key_base: 4e4b7d8d1cbd91a721162bd3f20f96a52d16ab50decc38b8cb703f8e6b255e3543ea2843f647c38b5bba05f61fa2eb1638cd1b206b0ef82827ac09a6ea3a90e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
